### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by wcxiaoping** [ip4-team/cnvfinder#13]
Hi! I installed CNVfinder using the pip3 command "pip install cnvfinder".  But I got the following error message:
>>> from cnvfinder import CNVConfig
>>> CNVConfig('filename.ini')
Loading .bed data.
Loading amplicons...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/libin/anaconda3/lib/python3.6/site-packages/cnvfinder/cnvdetector/cnvdetector.py", line 191, in __init__
    nrrtest = NRRConfig(filename).nrrtest if ratio else None
  File "/home/libin/anaconda3/lib/python3.6/site-packages/cnvfinder/nrrhandler/nrrhandler.py", line 853, in __init__
    bedfile=self.config.sections['bed']['bedfile'])
  File "/home/libin/anaconda3/lib/python3.6/site-packages/cnvfinder/nrrhandler/nrrhandler.py", line 106, in __init__
    self._bed = self.bed = bed
  File "/home/libin/anaconda3/lib/python3.6/site-packages/cnvfinder/nrrhandler/nrrhandler.py", line 138, in bed
    self._bed = ROI(self.bedfile)
  File "/home/libin/anaconda3/lib/python3.6/site-packages/cnvfinder/bedloader/bedloader.py", line 74, in __init__
    self.amplicons = self.load_amplicons(lines, maxpool, 8)
  File "/home/libin/anaconda3/lib/python3.6/site-packages/cnvfinder/bedloader/bedloader.py", line 100, in load_amplicons
    newamplicon = Amplicon(line, pool_loc, maxpool)
  File "/home/libin/anaconda3/lib/python3.6/site-packages/cnvfinder/bedloader/bedloader.py", line 194, in __new__
    pools = beddata[pool_loc]
IndexError: list index out of range

Can you tell me what's wrong? Thanks

**Comment by valengo** [comment]
Hi! Can you provide the first lines of the BED file you are using? It seems that the input bed file has fewer columns than the default bed file from Thermo Fisher (e.g. AmpliSeqExome.20141113.designed.bed) and the pool data (e.g. GENE_ID=OR4F5;Pool=5) is not in the expected column

**Comment by wcxiaoping** [comment]
I'm sorry to reply you so late. There are only three  columns in my input  bed file: chrom, chromStart, chromEnd. Can you provide me a demo bed file? Thank you very much!

**Comment by valengo** [comment]
Hi!
Currently, cnvfinder needs a BED that specifies the pools that each target is originated from. You can see a mock of the current needed BED file on https://github.com/ip4-team/bedhandler/blob/master/test/handler/mocks/ampliseq_exome.bed and you can (after registration or login) obtain the complete designed BED file from http://ampliseq.com, there you'll find a list of "ready-to-use" panels, including the created for exome, for instance: "Ion AmpliSeq™ Exome Panel".

We use pool data for standardization and we're currently only supporting data obtained from Ion Torrent
platforms (Thermo Fisher Scientific). What type of data are you working on? Was it generated from amplicon-based enrichment technologies? 

Are you trying to use cnvfinder for CNV detection itself or do you want to do something else?

**Comment by wcxiaoping** [comment]
Thank you for your help. Recently, I've been testing the accuracy of some CNV detection  software. But most of my data obtained from illumina platforms .

**Comment by valengo** [comment]
You're welcome!
I see. Unless you start working on data obtained with AmpliSeq for Illumina, you won't need to use cnvfinder for CNV detection. Based on this issue, I'm going to update the docs.
Thanks for your interest on testing our tool!
